import { generateId } from '../lib/utils';
import type { Post, Live, Phase, Offer, Persona } from '../types';

export function generateSeedPosts(): Post[] {
  const now = new Date().toISOString();
  return [
    {
      id: generateId(),
      platform: 'facebook',
      type: 'text',
      theme: 'migration',
      tone: 'provocative',
      language: 'frenchy',
      status: 'published',
      scheduledDate: now,
      createdAt: now,
      updatedAt: now,
      title: 'Pourquoi Facebook peut te fermer ta page demain',
      content: {
        hook: 'Imagine: tu te réveilles demain et ta page Facebook avec 50k abonnés a disparu.',
        body: 'C\'est arrivé à des milliers de vendeurs algériens. Tu n\'es pas propriétaire de tes abonnés Facebook. Alors que ton site web ? C\'est TOI qui contrôle. Tu peux collecter les emails, retargeter les visiteurs, et surtout dormir tranquille.',
        cta: 'Commente "SITE" si tu veux savoir comment migrer en 30 jours.',
        hashtags: ['#EcommerceDZ', '#MigrationFB', '#SEOAlgerie', '#BusinessOnline'],
        recommendedHour: '19:00',
        engagementScore: 85,
      },
      isFavorite: false,
      tags: ['viral', 'migration'],
    },
    {
      id: generateId(),
      platform: 'instagram',
      type: 'carousel',
      theme: 'seo',
      tone: 'educational',
      language: 'french',
      status: 'scheduled',
      scheduledDate: new Date(Date.now() + 86400000).toISOString(),
      createdAt: now,
      updatedAt: now,
      title: '5 erreurs SEO qui tuent ton site',
      content: {
        hook: 'Ton site est invisible sur Google ? Voici pourquoi.',
        body: '1. Tu n\'as pas de sitemap\n2. Tes images sont trop lourdes\n3. Tu n\'utilises pas de mots-clés locaux\n4. Ton site n\'est pas responsive\n5. Tu n\'as pas de backlinks',
        cta: 'Sauvegarde ce post et applique une erreur par jour.',
        hashtags: ['#SEO', '#Algerie', '#SiteWeb', '#Google'],
        recommendedHour: '12:00',
        engagementScore: 72,
      },
      isFavorite: true,
      tags: ['seo', 'education'],
    },
    {
      id: generateId(),
      platform: 'tiktok',
      type: 'reel',
      theme: 'ai',
      tone: 'inspiring',
      language: 'darija',
      status: 'idea',
      createdAt: now,
      updatedAt: now,
      title: 'كيفاش IA تقدر تخدم لك 24/24',
      content: {
        hook: 'راك تخدم بيدك و ال IA تقدر تخدم لك وحدها؟',
        body: 'ChatGPT, Claude, Gemini... هادو مجرد أدوات. المهم كيفاش تستعملهم. أنا نستعمل IA باش نكتب مقالات SEO, نجاوب على clients, و ن analyse المنافسين. الكل في 2 ساعات فقط.',
        cta: 'Followi للمزيد و commente "AI" باش نبعثلك ال tools.',
        hashtags: ['#IA', '#Automatisation', '#Algerie', '#Business'],
        recommendedHour: '20:00',
        engagementScore: 90,
      },
      isFavorite: false,
      tags: ['ia', 'automatisation'],
    },
    {
      id: generateId(),
      platform: 'youtube',
      type: 'text',
      theme: 'ecommerce',
      tone: 'storytelling',
      language: 'french',
      status: 'written',
      createdAt: now,
      updatedAt: now,
      title: 'De 0 à 500k DZD/mois en e-commerce',
      content: {
        hook: 'En 2022, j\'avais 2000 DZD dans mon compte et zéro idée de business.',
        body: 'Aujourd\'hui, je gère 3 boutiques en ligne. Comment ? En appliquant les bases : un bon produit, un site optimisé, et du trafic organique. Pas de pub payante. Juste du travail intelligent.',
        cta: 'Abonne-toi pour la suite de mon parcours.',
        hashtags: ['#Ecommerce', '#SuccessStory', '#Algerie', '#Business'],
        recommendedHour: '18:00',
        engagementScore: 88,
      },
      isFavorite: false,
      tags: ['ecommerce', 'story'],
    },
    {
      id: generateId(),
      platform: 'linkedin',
      type: 'article',
      theme: 'personal_brand',
      tone: 'educational',
      language: 'french',
      status: 'idea',
      createdAt: now,
      updatedAt: now,
      title: 'Construire une marque personnelle sur LinkedIn en 2024',
      content: {
        hook: 'Votre marque personnelle est votre meilleur actif professionnel.',
        body: 'Sur LinkedIn Algérie, moins de 1% des utilisateurs publient régulièrement. C\'est une opportunité énorme. Postez une fois par jour. Partagez vos échecs. Donnez plus que vous ne demandez.',
        cta: 'Connectons-nous et échangeons sur vos projets.',
        hashtags: ['#PersonalBranding', '#LinkedIn', '#Algerie', '#Carrière'],
        recommendedHour: '09:00',
        engagementScore: 65,
      },
      isFavorite: false,
      tags: ['linkedin', 'branding'],
    },
    {
      id: generateId(),
      platform: 'facebook',
      type: 'text',
      theme: 'myth',
      tone: 'provocative',
      language: 'frenchy',
      status: 'published',
      scheduledDate: new Date(Date.now() - 172800000).toISOString(),
      createdAt: now,
      updatedAt: now,
      title: 'Le mythe du "je vais lancer ma pub Facebook"',
      content: {
        hook: 'La pub Facebook, c\'est pas une baguette magique.',
        body: 'Tout le monde croit que payer 5000 DZD de pub = des clients. Faux. Sans site web, sans tunnel de vente, sans email capture, tu jettes ton argent. La pub c\'est l\'accélérateur, pas le moteur.',
        cta: 'Partage ce post avec un ami qui veut lancer des pubs bêtement.',
        hashtags: ['#FacebookAds', '#Mythe', '#EcommerceDZ', '#Business'],
        recommendedHour: '19:30',
        engagementScore: 92,
      },
      isFavorite: true,
      tags: ['myth', 'facebook'],
    },
    {
      id: generateId(),
      platform: 'instagram',
      type: 'text',
      theme: 'advice',
      tone: 'inspiring',
      language: 'french',
      status: 'scheduled',
      scheduledDate: new Date(Date.now() + 172800000).toISOString(),
      createdAt: now,
      updatedAt: now,
      title: '3 habitudes qui changent tout',
      content: {
        hook: 'Ces 3 habitudes m\'ont fait passer de zéro à 6 chiffres.',
        body: '1. Lire 30 min par jour sur ton domaine\n2. Publier un contenu chaque jour, même quand t\'as pas envie\n3. Analyser tes chiffres chaque semaine sans exception',
        cta: 'Quelle habitude tu vas adopter cette semaine ?',
        hashtags: ['#Habitudes', '#Productivité', '#Entrepreneuriat', '#DZ'],
        recommendedHour: '07:00',
        engagementScore: 78,
      },
      isFavorite: false,
      tags: ['habitudes', 'conseil'],
    },
    {
      id: generateId(),
      platform: 'tiktok',
      type: 'reel',
      theme: 'success_story',
      tone: 'storytelling',
      language: 'darija',
      status: 'idea',
      createdAt: now,
      updatedAt: now,
      title: 'كيفاش بديت من البيت و وليت نبيع في أوروبا',
      content: {
        hook: '2020: كنت نبيع من دارنا في باب الزوار. 2024: نبيع في فرنسا و إسبانيا.',
        body: 'السر؟ DropShipping + SEO. درت site web، درت المحتوى، و خليت Google يجيب لي clients. ما درتش ولا دينار pub. ال traffic organique هو ال king.',
        cta: 'Followi باش تعرف الطريقة بالتفصيل.',
        hashtags: ['#Dropshipping', '#Success', '#Algerie', '#Ecommerce'],
        recommendedHour: '21:00',
        engagementScore: 95,
      },
      isFavorite: false,
      tags: ['success', 'dropshipping'],
    },
    {
      id: generateId(),
      platform: 'youtube',
      type: 'text',
      theme: 'migration',
      tone: 'educational',
      language: 'french',
      status: 'written',
      createdAt: now,
      updatedAt: now,
      title: 'Tutoriel complet : Migrer de Facebook à ton site',
      content: {
        hook: 'Guide étape par étape pour ne plus dépendre de Facebook.',
        body: 'Étape 1: Choisir son nom de domaine .dz\nÉtape 2: Installer WordPress ou Shopify\nÉtape 3: Migrer sa liste de produits\nÉtape 4: Configurer le paiement CCP / BaridiMob\nÉtape 5: Optimiser le SEO local\nÉtape 6: Créer un blog pour attirer du trafic',
        cta: 'Télécharge ma checklist gratuite en commentaire.',
        hashtags: ['#Tutoriel', '#Migration', '#SiteWeb', '#Ecommerce'],
        recommendedHour: '17:00',
        engagementScore: 80,
      },
      isFavorite: false,
      tags: ['tutoriel', 'migration'],
    },
    {
      id: generateId(),
      platform: 'linkedin',
      type: 'article',
      theme: 'ai',
      tone: 'provocative',
      language: 'french',
      status: 'idea',
      createdAt: now,
      updatedAt: now,
      title: 'L\'IA ne remplacera pas les entrepreneurs algériens',
      content: {
        hook: 'L\'IA est un outil. Vous êtes le stratège.',
        body: 'Trop de gens paniquent à cause de l\'IA. La vérité ? L\'IA ne peut pas prendre des décisions business, ne peut pas comprendre le marché algérien, et ne peut pas construire une relation de confiance. Elle accélère ceux qui savent déjà quoi faire.',
        cta: 'Quel est votre avis ? Partagez en commentaire.',
        hashtags: ['#IA', '#Entrepreneuriat', '#Algerie', '#Futur'],
        recommendedHour: '10:00',
        engagementScore: 70,
      },
      isFavorite: false,
      tags: ['ia', 'débat'],
    },
  ];
}

export function generateSeedLives(): Live[] {
  const now = new Date().toISOString();
  return [
    {
      id: generateId(),
      platform: 'fb_live',
      theme: 'Comment migrer de Facebook vers un site web en 2024',
      duration: '60',
      objective: 'educate',
      createdAt: now,
      isFavorite: true,
      content: {
        titles: [
          'Migration FB → Site : Le Guide Complet',
          'Pourquoi ton business FB est en danger',
          'Comment construire un site qui vend en Algérie',
        ],
        hook: 'Salam tout le monde ! Aujourd\'hui on parle de quelque chose qui fait peur à beaucoup de vendeurs : quitter Facebook pour avoir son propre site web. Mais ne vous inquiétez pas, je vais tout vous expliquer étape par étape.',
        minutePlan: [
          { minute: 0, topic: 'Introduction + Hook', duration: 5 },
          { minute: 5, topic: 'Pourquoi Facebook n\'est pas suffisant', duration: 10 },
          { minute: 15, topic: 'Les erreurs à éviter quand on migre', duration: 10 },
          { minute: 25, topic: 'Les outils nécessaires', duration: 10 },
          { minute: 35, topic: 'Q&A avec les viewers', duration: 15 },
          { minute: 50, topic: 'Offre spéciale + CTA final', duration: 10 },
        ],
        keyPoints: [
          'Facebook peut fermer ta page sans prévenir',
          'Un site web = propriété digitale',
          'Le SEO est le meilleur investissement long terme',
          'CCP et BaridiMob sont suffisants pour démarrer',
        ],
        interactions: [
          'Minute 10 : Demander qui a déjà un site',
          'Minute 25 : Sondage : Shopify vs WordPress',
          'Minute 40 : Lire les questions en commentaires',
        ],
        finalCta: 'Inscrivez-vous à ma formation gratuite "Migration Express" via le lien en bio. Places limitées !',
        announcementTexts: {
          facebook: '🔥 LIVE CE SOIR 19h ! Comment migrer de Facebook vers un site web en 2024. Je réponds à TOUTES vos questions.',
          instagram: '🎥 Live ce soir ! Si tu vends sur Facebook, tu DOIS venir. On parle migration, site web et indépendance.',
          tiktok: 'Live ce soir ! Pourquoi Facebook peut te fermer ta page demain ? Viens découvrir la solution.',
          youtube: '🔴 LIVE ce soir 19h - Migration FB → Site Web : Le guide complet pour vendeurs algériens.',
          linkedin: 'Live professionnel ce soir : Stratégie de migration digitale pour e-commerçants algériens.',
        },
        techChecklist: [
          'Son clair (micro ou écouteurs)',
          'Éclairage face à soi',
          'Batterie à 100% ou branché',
          'Connexion WiFi stable',
          'Fermer les notifications',
          'Préparer un verre d\'eau',
        ],
        faq: [
          {
            question: 'Combien coûte un site web ?',
            answer: 'Un site WordPress de base coûte entre 15 000 et 30 000 DZD par an (hébergement + thème). C\'est un investissement, pas une dépense.',
          },
          {
            question: 'Est-ce que je vais perdre mes clients ?',
            answer: 'Au contraire, vous allez en gagner plus. Vos clients Facebook restent, mais vous allez en attirer de nouveaux via Google.',
          },
        ],
      },
    },
    {
      id: generateId(),
      platform: 'ig_live',
      theme: 'SEO pour débutants : comment apparaître sur Google',
      duration: '90',
      objective: 'sell',
      createdAt: now,
      isFavorite: false,
    },
    {
      id: generateId(),
      platform: 'tt_live',
      theme: 'Comment utiliser l\'IA pour automatiser ton business',
      duration: '30',
      objective: 'engage',
      createdAt: now,
      isFavorite: false,
    },
  ];
}

export function generateSeedPhases(): Phase[] {
  return [
    {
      id: generateId(),
      name: 'Phase 1 : Fondations & Visibilité',
      days: 'J1-30',
      objectives: [
        'Créer et optimiser les profils sociaux',
        'Lancer le site web de base',
        'Publier 1 contenu par jour minimum',
      ],
      actions: [
        'Auditer la présence actuelle',
        'Définir la charte graphique',
        'Créer 30 idées de posts',
        'Configurer Google Analytics',
        'Optimiser le SEO on-page',
      ],
      metrics: [
        '500 abonnés Facebook',
        '300 abonnés Instagram',
        '1000 visites sur le site',
        '50 leads collectés',
      ],
    },
    {
      id: generateId(),
      name: 'Phase 2 : Autorité & Communauté',
      days: 'J31-60',
      objectives: [
        'Devenir la référence dans la niche',
        'Construire une communauté engagée',
        'Lancer le blog et le podcast/YouTube',
      ],
      actions: [
        'Publier 2 contenus par jour',
        'Faire 2 Lives par semaine',
        'Collaborer avec 3 micro-influenceurs',
        'Lancer une newsletter hebdomadaire',
        'Répondre à tous les commentaires',
      ],
      metrics: [
        '1500 abonnés Facebook',
        '1000 abonnés Instagram',
        '5000 visites mensuelles',
        '200 leads/mois',
        '5% de taux d\'engagement',
      ],
    },
    {
      id: generateId(),
      name: 'Phase 3 : Monétisation',
      days: 'J61-90',
      objectives: [
        'Lancer les 3 offres',
        'Automatiser la vente',
        'Scalér avec de la pub payante',
      ],
      actions: [
        'Lancer l\'offre d\'audit',
        'Ouvrir les inscriptions à la formation',
        'Signer les premiers clients accompagnement',
        'Mettre en place les funnels de vente',
        'Lancer des pubs Facebook ciblées',
      ],
      metrics: [
        '3000 abonnés Facebook',
        '2500 abonnés Instagram',
        '15 000 visites mensuelles',
        '500 leads/mois',
        '10 clients signés',
        '100 000 DZD de revenus',
      ],
    },
  ];
}

export function generateSeedOffers(): Offer[] {
  return [
    {
      id: generateId(),
      name: 'Audit + Migration FB → Site',
      description:
        'Audit complet de ta présence Facebook + création d\'un site web optimisé avec migration de ton catalogue produits. Livrable en 7 jours.',
      price: '25 000 DZD',
      type: 'service',
      pipeline: [
        'Appel découverte (30 min)',
        'Audit et proposition',
        'Paiement 50%',
        'Création du site',
        'Révision et validation',
        'Paiement final + livraison',
      ],
    },
    {
      id: generateId(),
      name: 'Formation "Indépendance Digitale"',
      description:
        'Formation complète en vidéo : créer son site, faire du SEO, utiliser l\'IA, et vendre sans dépendre de Facebook. Accès à vie + groupe privé.',
      price: '9 900 DZD',
      type: 'product',
      pipeline: [
        'Tunnel de vente (landing page)',
        'Séquence email de nurture',
        'Webinaire gratuit',
        'Offre limitée 48h',
        'Paiement en ligne',
        'Accès immédiat',
      ],
    },
    {
      id: generateId(),
      name: 'Accompagnement Mensuel',
      description:
        'Coaching personnalisé : 2 calls par mois, stratégie de contenu, review des KPIs, accès direct par WhatsApp. Minimum 3 mois.',
      price: '15 000 DZD/mois',
      type: 'recurring',
      pipeline: [
        'Appel de qualification',
        'Proposition personnalisée',
        'Essai 7 jours à 5000 DZD',
        'Paiement mensuel automatique',
        'Onboarding + plan personnalisé',
        'Suivi hebdomadaire',
      ],
    },
  ];
}

export function generateSeedPersonas(): Persona[] {
  return [
    {
      id: generateId(),
      name: 'Vendeur FB débutant',
      description: 'Vend des produits sur Facebook depuis moins de 6 mois. 0 à 20k DZD/mois.',
      painPoints: [
        'Ne sait pas comment créer un site web',
        'Peur de perdre ses clients',
        'Manque de confiance technique',
        'Budget limité',
      ],
      desires: [
        'Avoir un site professionnel',
        'Gagner la confiance des clients',
        'Arrêter de dépendre de Facebook',
        'Augmenter ses ventes',
      ],
      objections: [
        'C\'est trop cher',
        'C\'est trop compliqué',
        'Je n\'ai pas le temps',
        'Mes clients sont sur Facebook',
      ],
      keyMessage:
        'Commencer petit avec un site simple coûte moins cher que tu ne penses et te protège pour l\'avenir.',
    },
    {
      id: generateId(),
      name: 'Vendeur FB établi',
      description: 'Vend sur Facebook depuis 1-2 ans. 50-200k DZD/mois.',
      painPoints: [
        'La concurrence est de plus en plus forte',
        'Les algos FB réduisent la portée',
        'Les clients négocient trop',
        'Pas de données clients exploitables',
      ],
      desires: [
        'Scalér son business',
        'Avoir un système de vente automatisé',
        'Se positionner comme expert',
        'Attirer des clients de meilleure qualité',
      ],
      objections: [
        'Ça marchait bien avant pourquoi changer ?',
        'J\'ai déjà essayé un site, ça n\'a pas marché',
        'Je n\'ai pas le temps de gérer un site',
      ],
      keyMessage:
        'Un site web + SEO = un canal d\'acquisition que personne ne peut te fermer. C\'est l\'assurance-vie de ton business.',
    },
    {
      id: generateId(),
      name: 'Gros vendeur FB',
      description: 'Gère une boutique avec équipe. 300k+ DZD/mois. Cherche à scaler.',
      painPoints: [
        'Le business dépend trop d\'une seule personne',
        'Difficulté à recruter et former',
        'Pas de processus documentés',
        'Croissance bloquée par la capacité',
      ],
      desires: [
        'Créer une vraie entreprise',
        'Automatiser 80% des tâches',
        'Passer à l\'international',
        'Lever des fonds ou vendre',
      ],
      objections: [
        'J\'ai déjà une équipe qui gère',
        'Les changements prennent trop de temps',
        'Je préfère investir dans les pubs',
      ],
      keyMessage:
        'Pour scaler de 300k à 3M, il te faut des systèmes. L\'IA et le SEO sont tes leviers de croissance.',
    },
    {
      id: generateId(),
      name: 'Étudiant entrepreneur',
      description: 'Étudiant algérien qui veut créer un revenu en ligne. Tech-savvy.',
      painPoints: [
        'Manque de capital de départ',
        'Peur de l\'échec',
        'Pas de mentor',
        'Trop d\'informations contradictoires',
      ],
      desires: [
        'Gagner son indépendance financière',
        'Travailler de n\'importe où',
        'Apprendre des compétences demandées',
        'Créer quelque chose à soi',
      ],
      objections: [
        'Je n\'ai pas d\'expérience',
        'Le marché est saturé',
        'Je dois finir mes études d\'abord',
      ],
      keyMessage:
        'Commencer jeune est un avantage. Avec les bonnes compétences (SEO, IA), tu peux surpasser les "expérimentés".',
    },
    {
      id: generateId(),
      name: 'Freelance / Consultant',
      description: 'Prestataire de services qui veut attirer des clients en ligne.',
      painPoints: [
        'Trouve ses clients sur des groupes Facebook',
        'Tarifs trop bas car pas de positionnement',
        'Manque de visibilité professionnelle',
        'Clients difficiles qui négocient',
      ],
      desires: [
        'Attirer des clients qualifiés',
        'Facturer plus',
        'Avoir une file d\'attente de clients',
        'Être reconnu comme expert',
      ],
      objections: [
        'Je ne suis pas "vendeur"',
        'Le marketing, c\'est pas pour moi',
        'Je préfère le bouche-à-oreille',
      ],
      keyMessage:
        'Un personal brand fort + un site optimisé = des clients qui viennent à TOI et acceptent TES tarifs.',
    },
  ];
}
